# -*- coding: utf-8 -*-
"""stats_final_lab12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZfENbxrBXfGHSJJPyjKrSc11cqCtMCY

**อย่าลืม Save a copy in drive ก่อนนะคะ**

จงเขียนโปรแกรมเพื่อหาค่าที่โจทย์ต้องการและแสดงผลลัพธ์ออกทางหน้าจอ

1. 	ในการศึกษาโภชนศาสตร์เกี่ยวกับอาหาร fast food ยี่ห้อหนึ่ง โดยสุ่มแฮมเบอร์เกอร์ 35 ชิ้น ได้ข้อมูล ดังนี้

39.9 39.1 27.8 34.2 30.3 25.7 33.2 28.0 18.9 23.8 29.9 39.0 35.0 30.4 28.9 15.9 35.2 24.3 19.4 27.3 37.4 24.3 33.4 14.5 16.0 21.1 36.4 33.4 22.0 36.7 30.7 34.7 23.1 28.8 38.8

  1.1 จงวาดกราฟความหนาแน่นของข้อมูลชุดนี้เพื่อตรวจสอบว่าข้อมูลชุดนี้มีการแจกแจงแบบปกติหรือไม่

   1.2  จงประมาณค่าแบบจุดของข้อมูลน้ําหนักไขมันเฉลี่ยในแฮมเบอร์เกอร์ยี่ห้อนี้

  1.3 จงประมาณค่าแบบช่วงของข้อมูลน้ําหนักไขมันเฉลี่ยในแฮมเบอร์เกอร์ยี่ห้อนี้ ด้วยความเชื่อมั่น 99%

 1.4 จงทดสอบว่าข้อมูลนำหนักไขมันเฉลี่ยนี้มากจากประชากรที่มีการแจกแจงแบบปกติหรือไม่

2. เม่ือต้องการประมาณจานวนคร้ังขอบการเต้นของหัวใจโดยเฉล่ียต่อนาทีของประชากรกลุ่มหน่ึง จึง สุ่มบุคคลากรจากประชากรกลุ่มน้ีมาจานวน 15 คน ดังนี้ ถ้าประชากรมีการแจกแจงแบบปกติ จงตอบคาถาม ต่อไปนี้
87, 89, 95, 90, 91, 92, 93, 95, 90, 89, 88, 87, 92, 93, 89

2.1 จงหาช่วงความเช่ือม่ัน 90% ของจานวนคร้ังของการเต้นของหัวใจโดยเฉล่ีย

2.2 จงหาช่วงความเช่ือม่ัน 95% ของจานวนคร้ังของการเต้นของหัวใจโดยเฉล่ีย


3. สุ่มตัวอย่างหญิงไทยที่สิ้นชีวิตไปในที่ผานมา 28 คน พบว่ามีอายุเป็น
85 59 60 98 66 78 76 62 61 66 82 68 72 76 76 70 73 71 87 69 68 70 70 69 78 75 65 73 
จากข้อมูลดังกล่าวสามารถยืนยันได้หรือไม่ว่าอายุเฉลี่ยที่แท้จริงของหญิงไทยในปัจจุบัน มากกว่า 70 ปี โดยใช้ระดับนัยสําคัญ 0.1
"""

#1.1 จงวาดกราฟความหนาแน่นของข้อมูลชุดนี้เพื่อตรวจสอบว่าข้อมูลชุดนี้มีการแจกแจงแบบปกติหรือไม่
import pandas as pd
df = pd.DataFrame({'expense':[39.9, 39.1, 27.8, 34.2 ,30.3 ,25.7 ,33.2 ,28.0, 18.9 ,23.8 ,29.9, 39.0 ,35.0 ,
                              30.4 ,28.9 ,15.9 ,35.2 ,24.3 ,19.4 ,27.3 ,37.4 ,24.3, 33.4, 14.5, 16.0 ,21.1 ,36.4, 33.4 ,22.0 ,36.7 ,
                              30.7 ,34.7 ,23.1, 28.8 ,38.8]})

ax = df.plot(kind='density',figsize=(10,4),title="Expense",legend=False)
ax.set_xlabel("Expense")
ax.set_ylabel("Density")
print(df.mean())
#ans = แจกแจงปกติ และค่าเฉลี่ย = 29.07

#1.31.3 จงประมาณค่าแบบช่วงของข้อมูลน้ําหนักไขมันเฉลี่ยในแฮมเบอร์เกอร์ยี่ห้อนี้ ด้วยความเชื่อมั่น 99%
from scipy.stats import t,sem
from statistics import mean
data = [39.9, 39.1, 27.8, 34.2 ,30.3 ,25.7 ,33.2 ,28.0, 18.9 ,23.8 ,29.9, 39.0 ,35.0 ,
        30.4 ,28.9 ,15.9 ,35.2 ,24.3 ,19.4 ,27.3 ,37.4 ,24.3, 33.4, 14.5, 16.0 ,21.1 ,36.4, 33.4 ,22.0 ,36.7 ,
        30.7 ,34.7 ,23.1, 28.8 ,38.8]
confidence_level = 0.99
df = len(data)-1
mean_ = mean(data)
std = sem(data)
confidence_interval = t.interval(confidence_level,df,mean_,std)
print(confidence_interval)

#1.4จงทดสอบว่าข้อมูลนำหนักไขมันเฉลี่ยนี้มากจากประชากรที่มีการแจกแจงแบบปกติหรือไม่
from scipy.stats import anderson
data = [39.9, 39.1, 27.8, 34.2 ,30.3 ,25.7 ,33.2 ,28.0, 18.9 ,23.8 ,29.9, 39.0 ,35.0 ,
        30.4 ,28.9 ,15.9 ,35.2 ,24.3 ,19.4 ,27.3 ,37.4 ,24.3, 33.4, 14.5, 16.0 ,21.1 ,36.4, 33.4 ,22.0 ,36.7 ,
        30.7 ,34.7 ,23.1, 28.8 ,38.8]
result = anderson(data)
print(result)
print('Result = %.3f'%result.statistic)

for i in range(len(result.critical_values)):
  sl, cv = result.significance_level[i], result.critical_values[i]
  if result.statistic < result.critical_values[i]:
    print('%.3f: %.3f, data looks normal(accept H0)' %(sl, cv))
  else:
    print('%.3f: %.3f, data doesn’t look normal(reject H0)' %(sl,cv))

#1.4 V.2
from scipy.stats import shapiro
data= [39.9 ,39.1, 27.8, 34.2, 30.3, 25.7, 33.2, 28.0 ,18.9, 23.8 ,29.9 ,39.0 ,35.0 ,30.4, 28.9, 15.9, 35.2, 24.3 ,19.4 ,27.3 ,37.4 ,24.3, 33.4, 14.5, 16.0, 21.1, 36.4, 33.4, 22.0, 36.7 ,30.7, 34.7 ,23.1, 28.8 ,38.8]
stat,p = shapiro(data)
print('stat = %.3f, p = %.3f\n' %(stat,p))
if p> 0.05:
  print('Probably Normal')
else:
  print(('Probably not Normal'))

"""แจกแจงปกติ"""

#2.1จงหาช่วงความเช่ือม่ัน 90% ของจานวนคร้ังของการเต้นของหัวใจโดยเฉล่ีย
from scipy.stats import t,sem
from statistics import mean
data =[87, 89, 95, 90, 91, 92, 93, 95, 90, 89, 88, 87, 92, 93, 89]
confidence_level = 0.90
df = len(data)-1
sam_mean = mean(data)
std = sem(data)
confidence_interval = t.interval(confidence_level,df,sam_mean,std)
print(confidence_interval)

#2.2จงหาช่วงความเช่ือม่ัน 95% ของจานวนคร้ังของการเต้นของหัวใจโดยเฉล่ีย
from scipy.stats import t,sem
from statistics import mean
data =[87, 89, 95, 90, 91, 92, 93, 95, 90, 89, 88, 87, 92, 93, 89]
confidence_level = 0.95
df = len(data)-1
sam_mean = mean(data)
std = sem(data)
confidence_interval = t.interval(confidence_level,df,sam_mean,std)
print(confidence_interval)

#3.สุ่มตัวอย่างหญิงไทยที่สิ้นชีวิตไปในช่วงเวลาที่ผานมา 28 คน พบว่ามีอายุเป็น 
#85 59 60 98 66 78 76 62 61 66 82 68 72 76 76 70 73 71 87 69 68 70 70 69 78 75 65 73 
#จากข้อมูลดังกล่าวสามารถยืนยันได้หรือไม่ว่าอายุเฉลี่ยที่แท้จริงของหญิงไทยในปัจจุบัน มากกว่า 70 ปี โดยใช้ระดับนัยสําคัญ 0.1
#1.เป็นข้อมูลขนาดเล็ก หาแจกแจงปกติมั้ยใช้ shapiro
from scipy.stats import shapiro
from scipy.stats import ttest_1samp

data = [87, 89, 95, 90, 91, 92, 93, 95, 90, 89, 88, 87, 92, 93, 89]
result = shapiro(data)
print('stat = %.3f, p = %.3f\n' %(stat,p))
if p> 0.05:
  print('Probably Normal')
else:
  print(('Probably not Normal'))
'''สมมุติฐานคือ อายุ > 70 ปี
u <= 70:H0
u >70 :H1 '''

data= [ 85, 59, 60, 98, 66, 78, 76, 62, 61, 66, 82, 68, 72, 76, 76, 70, 73, 71, 87, 69, 68, 70, 70, 69, 78, 75, 65, 73]
popmean = 70
stat, p = ttest_1samp(data, popmean)
p = p/2 # left-tailed ,t < 0
# In case left-tailed, t > 0 then p = 1-(p/2)
print('stat = %.7f, p = %.7f\n' %(stat,p))
if p < 0.1: # alpha value is 0.05 or 5%
  print(" we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")

